qdl: switch from anyhow to thiserror
This makes it possible for library users to match on errors.

Errors are also more descriptive now:

    Error: I/O error while reading
    
    Caused by:
       0: libusb error
       1: Overflow

Compared to what it was before:

    Error: other error

For some reasoning, see https://kazlauskas.me/entries/errors